spring:
  application:
    name: payment-later
    

#service-url
url:
  order-service: ${ORDER_SERVICE_URL:http://localhost:8085}
  payment-service: ${PAYMENT_SERVICE_URL:http://localhost:8086}
openapi:
  service:
    api-docs: payment-later-service
    server: http://localhost:${server.port}
    title: Payment later service
    version: 1.0.0
